using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Polar.HabboHotel.Items.Wired
{
    public enum WiredBoxType
    {
        None,
        TriggerRoomEnter,
        TriggerUserSays,
        TriggerRepeat,
        TriggerStateChanges,
        TriggerWalkOnFurni,
        TriggerWalkOffFurni,
        TriggerGameStarts,
        TriggerGameEnds,
        TriggerUserFurniCollision,
        TriggerUserSaysCommand,

        EffectCollisionCase,
        EffectShowMessage,
        EffectTeleportToFurni,
        EffectToggleFurniState,
        EffectKickUser,
        EffectMatchPosition,
        EffectMoveAndRotate,
        EffectMoveFurniToNearestUser,
        EffectMoveFurniFromNearestUser,
        EffectMuteTriggerer,
        EffectGiveReward,
        EffectExecuteWiredStacks,
        EffectAddScore,

        EffectTeleportBotToFurniBox,
        EffectBotChangesClothesBox,
        EffectBotMovesToFurniBox,
        EffectBotCommunicatesToAllBox,
        EffectBotCommunicatesToUserBox,
        EffectBotFollowsUserBox,
        EffectBotGivesHanditemBox,

        EffectAddActorToTeam,
        EffectRemoveActorFromTeam,
        EffectSetRollerSpeed,
        EffectRegenerateMaps,
        EffectGiveUserBadge,
        EffectGiveCurrency,
        EffectExecuteCommand,
        EffectGiveExperience,

        ConditionFurniHasUsers,
        ConditionFurniHasFurni,
        ConditionTriggererOnFurni,
        ConditionIsGroupMember,
        ConditionIsNotGroupMember,
        ConditionTriggererNotOnFurni,
        ConditionFurniHasNoUsers,
        ConditionIsWearingBadge,
        ConditionIsWearingFX,
        ConditionIsNotWearingBadge,
        ConditionIsNotWearingFX,
        ConditionMatchStateAndPosition,
        ConditionDontMatchStateAndPosition,
        ConditionUserCountInRoom,
        ConditionUserCountDoesntInRoom,
        ConditionFurniTypeMatches,
        ConditionFurniTypeDoesntMatch,
        ConditionFurniHasNoFurni,
        ConditionActorHasHandItemBox,
        ConditionNotActorHasHandItemBox,
        ConditionActorIsInTeamBox,
        ConditionHasJob,
        ConditionIsNight,
        ConditionIsDay,
        ConditionIsJailed,
        ConditionIsDead,
        EffectApplyEffect,
        ConditionIsDriving,
        EffectDamageUser,
        EffectHealUser,
        ConditionHasVip,
        EffectSetMotto,
        EffectFreezeUser,
        EffectUnfreezeUser,
        ConditionIsSitting,
        EffectGiveHuntPoints,
        EffectGiveEnergy,
        EffectGiveArmor,
        ConditionHasWeapon,
        EffectGiveRPItem,
        ConditionHasRPItem,
        EffectSetRotation,
        ConditionIsIdle,
        ConditionIsDancing,

        AddonRandomEffect,
        AddonAnimationTime,
        AddonExecuteInOrder,
        AddonExecutionLimit,
        AddonFilterFurni,
        AddonFilterUser,
        AddonMoveCarryUsers,
        AddonMoveNoAnimation,
        AddonMovePhysics,
        AddonOrEval,
        AddonRandom,
        AddonTextOutputFurniName,
        AddonTextOutputUsername,
        AddonUnseen,
        AddonUserVariable,
        AddonRoomVariable,
        AddonFurniVariable,
        SpecialHighscore,

        // Variable Wireds (from AM Extended)
        EffectSetVariable,
        EffectVariableAdd,
        EffectVariableSubtract,
        ConditionVariableIsEqual,
        ConditionVariableIsGreaterThan,
        ConditionVariableIsLessThan,

        // Additional AM Extended Wireds
        EffectTeleportToRoom,
        EffectGiveHanditem,
        EffectMoveFurniXYZ,

        // Selectors
        SelectorFurniAll,
        SelectorFurniRandom,
        SelectorUserAll,
        SelectorUserRandom,
        SelectorFurniByType,
        SelectorFurniOnTop
    }
}
